# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 557e67a35c86d001073b9558f573ee7995e27211309575a4593068a035d6e19cb0842a59d333296d8995dcd94d35a724f4c54383c725e42ead46573c35bbcf01

test:
  secret_key_base: 97686c478559cd262ad2bbed3dafdc4396c6aef19c2ef6fc74ddcd3e4d8d06984bdb8f2951f74703dc8416aaf88267a8f8ca646844820343863d07551be2496f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
